_BASE_: "Base-DeformDETR_L_R50_4x.yaml"
SOLVER:
  IMS_PER_BATCH: 16
MODEL:
  DETR:
    K_ONE2MANY: 5
    NUM_OBJECT_QUERIES_ONE2MANY: 900
    MIXED_SELECTION: True
    LOOK_FORWARD_TWICE: True
    DROPOUT: 0.0
