_BASE_: "Base-DeformDETR_L_R50_4x.yaml"
FIND_UNUSED_PARAM: False
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_backbone
  SWIN:
    SIZE: B-22k
    OUT_FEATURES: [1, 2, 3]
    USE_CHECKPOINT: True
  DETR:
    MIXED_SELECTION: True
    LOOK_FORWARD_TWICE: True
    DROPOUT: 0.0
