_BASE_: "BoxSup-H-DeformDETR_L_R50_2x_t900_group5.yaml"
FIND_UNUSED_PARAM: False
SOLVER:
  IMS_PER_BATCH: 32
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_backbone
  DETR:
    USE_CHECKPOINT: True
  SWIN:
      SIZE: B-22k
      OUT_FEATURES: [1, 2, 3]
      USE_CHECKPOINT: True


